### ISSUE TITLE
Suggestion: Update Usage Step for Student

### ISSUE THREAD

**Issue by SethVilla** [phpeterson-usf/autograder#6]
When I was following the Usage Step for Student guide

I did not know that I needed to run grade test to generate the necessary config file, and tried to create one based on the section info to set the tests path.

Not sure if the error is caused because the config sections were missing in my manual config, but saw an error complaining about [Canvas] missing in the config file

**Comment by phpeterson-usf** [comment]
Thanks for the suggestion. You might be the first non-USF person to use this!
