### ISSUE TITLE
`commit_hash` causing failure with `grade test`

### ISSUE THREAD

**Issue by colm-persona** [phpeterson-usf/autograder#9]
<img width="1170" alt="Screenshot 2024-03-04 at 4 44 03 PM" src="https://github.com/phpeterson-usf/autograder/assets/161365984/2f04d8fc-7a1c-4181-a3e7-7a1ecaffa7e9">

Student shared an issue with the latest autograder that caused `grade test` to fail. When I had them revert to a [previous commit](https://github.com/phpeterson-usf/autograder/commit/9e526859c19872d3464ee2df402bfa7e42e204f7) it worked so I think something was introduced with the last two commits. For context, their guest OS died and started fresh with the setup which gave them the [latest version of autograder](https://github.com/phpeterson-usf/autograder/commit/124630769835ba231f218b97c43d86659f34ea8c).

**Comment by phpeterson-usf** [comment]
Bummer. Fixed
